### ISSUE TITLE
 Spice of Life heart visual conflict with over loaded armour bar

### ISSUE THREAD

**Issue by Ozzymud** [W1nter-isHere/FC-Atomic-Space#12] opened 2021-01-05 22:48 UTC
Modpack version: Atomic Space 2.0.0a Release
Launcher: MultiMC

I went on a binge for the past hour eating as many new foods as I can, have had a full row of vanilla hearts the entire time even though I have leveled up several times.

![2021-01-05_14 44 47](https://user-images.githubusercontent.com/6426344/103708235-08a11e00-4f65-11eb-80b8-891933a9ee82.png)

![2021-01-05_14 45 11](https://user-images.githubusercontent.com/6426344/103708243-0b9c0e80-4f65-11eb-8c70-e0fb3938aa16.png)

**Comment by winterSteve25** [comment] 2021-01-05 22:57
This will be fixed in the next version, thanks for your report

**Comment by Ozzymud** [comment] 2021-01-05 23:47
So this is just visual? I don't much care about the armor bar, can I just disable that mod to get an accurate health bar?

**Comment by winterSteve25** [comment] 2021-01-05 23:51
I'm almost positive it's a visual thing but not 100 % sure

**Comment by winterSteve25** [comment] 2021-01-06 14:19
Yep it is visual and it is caused by overloader armor bar, it will be fixed in the next update

**Closed as completed by winterSteve25** 2021-01-06 14:19 UTC
Labels: bug
